# Generated by Django 6.0.1 on 2026-01-07 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название трека')),
                ('artist', models.CharField(max_length=200, verbose_name='Исполнитель')),
                ('lastfm_id', models.CharField(max_length=100, unique=True, verbose_name='Last.fm ID')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (сек)')),
                ('tags', models.TextField(blank=True, verbose_name='Теги/жанры (через запятую)')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('access_code', models.CharField(max_length=12, unique=True, verbose_name='Код доступа')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('ends_at', models.DateTimeField(verbose_name='Окончание голосования')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('max_genre_percent', models.PositiveSmallIntegerField(default=30, help_text='Максимальный процент треков одного жанра (от 1 до 100)', verbose_name='Макс. доля жанра (%)')),
                ('mood_sequence', models.CharField(choices=[('energetic_to_calm', 'Энергичный → Спокойный'), ('calm_to_energetic', 'Спокойный → Энергичный'), ('mixed', 'Смешанная')], default='energetic_to_calm', max_length=20, verbose_name='Последовательность настроения')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='TrackSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_score', models.IntegerField(default=0, verbose_name='Рейтинг голосов')),
                ('suggested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата предложения')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.event', verbose_name='Мероприятие')),
                ('suggested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Предложил')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.track', verbose_name='Трек')),
            ],
            options={
                'verbose_name': 'Предложение трека',
                'verbose_name_plural': 'Предложения треков',
                'unique_together': {('event', 'track')},
            },
        ),
    ]
