# Generated by Django 6.0.1 on 2026-01-11 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracksuggestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='tracksuggestion',
            name='votes_score',
        ),
        migrations.AddField(
            model_name='tracksuggestion',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tracksuggestion',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_genre_percent',
            field=models.PositiveSmallIntegerField(default=50, help_text='Максимальный процент треков одного жанра (от 1 до 100)', verbose_name='Макс. доля жанра (%)'),
        ),
        migrations.AlterField(
            model_name='tracksuggestion',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.event'),
        ),
        migrations.AlterField(
            model_name='tracksuggestion',
            name='suggested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tracksuggestion',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tracksuggestion',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.track'),
        ),
    ]
