# Generated by Django 4.2.27 on 2026-01-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_ends_at_alter_event_id_alter_track_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksuggestion',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.track'),
        ),
    ]
